# Scale factors for converting pixels to meters
scale_x: 5  # meters per pixel in x direction
scale_y: 0.005  # meters per pixel in y direction

# Origin offset in meters
camera_origin_x_pixels: 0.0   # x offset in pixels from image corner
camera_origin_y_pixels: 0.0   # y offset in pixels from image corner

cam_offset_rob_frame_x: 1.307  # x offset in meters from the robot 0 0
cam_offset_rob_frame_y: 0.8552 # y offset in meters from the robot 0 0
